feat(iam): adding gnosis safe stamp
gitcoinco/passport pull request #517
Opened 2022-08-29 18:15 UTC by nutrina

This closes #468

2022-08-30 07:54 UTC, aminah-io requested changes
Just one suggestion in the test 🤘

2022-08-30 07:54 UTC, aminah-io commented on iam/__tests__/gnosisSafe.test.ts
> +import { alchemyGetNFTsUrl, NFTProvider } from "../src/providers/nft";
```suggestion
```

2022-09-08 19:16 UTC, aminah-io approved these changes
LGTM 🚀 !!

2022-09-08 19:19 UTC, farque65 approved these changes

2022-09-08 19:23 UTC, merged