feat(app): adds Discord sidebar, toggle, and verify for Discord data point
gitcoinco/passport pull request #527
Opened 2022-09-02 11:43 UTC by aminah-io

2022-09-05 10:50 UTC, gdixon requested changes
Awesome! LGTM! 

We will need to update the doneToast's props when we rebase onto main (or the types will be off) - can you rebase this and we can start getting the done ones in?

2022-09-05 10:50 UTC, gdixon commented on app/components/PlatformCards/DiscordPlatform.tsx
> +            render: (result: any) => <DoneToastContent providerId={platformId} result={result} />,
```suggestion
            render: (result: any) => <DoneToastContent platformId={platformId} result={result} />,
```

2022-09-05 17:22 UTC, aminah-io commented on app/components/PlatformCards/DiscordPlatform.tsx
> +            render: (result: any) => <DoneToastContent providerId={platformId} result={result} />,
Done!

2022-09-06 12:49 UTC, gdixon approved these changes

2022-09-06 12:53 UTC, merged