feat(app): implements sidebar for Linkedin platform
gitcoinco/passport pull request #531
Opened 2022-09-02 15:02 UTC by gdixon

This PR exposes the Linkedin Provider via the Linkedin Platform sidebar.

--

Closes: #454,  closes: #455, closes: #454

2022-09-02 15:52 UTC, aminah-io requested changes
Just a couple of suggestions, otherwise LGTM 🚀 !

2022-09-02 15:52 UTC, aminah-io commented on app/components/PlatformCards/LinkedinPlatform.tsx
>  // Each provider is recognised by its ID
```suggestion
// Each platform is recognised by its ID
```

2022-09-02 15:52 UTC, aminah-io commented on app/components/PlatformCards/LinkedinPlatform.tsx
> +    STAMP_PROVIDERS["Facebook"]?.reduce((all, stamp) => {
```suggestion
    STAMP_PROVIDERS["Linkedin"]?.reduce((all, stamp) => {
```

2022-09-02 18:06 UTC, aminah-io approved these changes
LGTM 🚀 !!

2022-09-05 10:52 UTC, gdixon commented on app/components/PlatformCards/LinkedinPlatform.tsx
> +            render: (result: any) => <DoneToastContent providerId={platformId} result={result} />,
```suggestion
            render: (result: any) => <DoneToastContent platformId={platformId} result={result} />,
```

2022-09-05 10:56 UTC, merged